### ISSUE TITLE
Why can't GDC improve the performance of link prediction? Are there any intuitive and theoretical explanations?

### ISSUE THREAD

**Issue by CXX1113** [klicperajo/gdc#5]

**Comment by gasteigerjo** [comment]
First of, we haven't shown that it absolutely can't. We rather just found in our experiments that it doesn't.

My intuitive explanation for this is that since GDC changes the graph it necessarily loses some link information. This hurts link prediction performance, even if the smoothing done by GDC is beneficial for other tasks.
