### ISSUE TITLE
How to use GDC in large graph

### ISSUE THREAD

**Issue by junkangwu** [klicperajo/gdc#6]
As for some large graph which is difficult to deal with in the format of `AHX`, may I ask you about some advice or suggestion on this actual view(such as some knowledge graph) ?

**Comment by gasteigerjo** [comment]
I have no idea about the AHX format. Regarding knowledge graphs I'd give you the advice of first checking whether the homophily assumption that GDC is based on is fulfilled for your dataset. For large graphs I'd recommend using more scalable algorithms for PPR and the heat kernel instead of directly calculating T^{-1} and expm(T), as we do in this repository.

**Comment by junkangwu** [comment]
Thanks a lot
